    -   # This server
        type: current
        host: 127.0.0.1 # we ignore this...
        port: -1 # we ignore this...
        pass: # we ignore this...
        other:
            servers:
                gss.login.socket.connectors.KryoNetServer:
                        -
                            port: 100
                # gss.run.servers.connectors.Plain:

    -   # Login server (custom made)
        type: login
        host: 127.0.0.1
        port: 7780
        pass: # A password here

    -   # Database server (e.g. mysql)
        type: database
        host: 127.0.0.1
        port: 7781
        pass: # A password here
        other:
            hibernate.connection.driver_class: org.hsqldb.jdbcDriver
            hibernate.connection.url: jdbc:hsqldb:{configDir}/database/database.db
            hibernate.connection.username: "SA"
            hibernate.connection.password: ""
            hibernate.dialect: org.hibernate.dialect.HSQLDialect
            hibernate.current_session_context_class: thread
            hibernate.transaction.factory_class: org.hibernate.transaction.JDBCTransactionFactory
            hibernate.cache.provider_class: org.hibernate.cache.NoCacheProvider
            hibernate.connection.pool_size: 1
            hibernate.connection.autocommit: true
            hibernate.hbm2ddl.auto: create-drop
            hibernate.show_sql: true

    -   # Content server (e.g. apache2)
        type: content
        host: 127.0.0.1
        port: 7782
        pass: # A password here
        other:
            directory: {gameVersion}
            # I'm just guessing.. for a multi game storage content server with different versions

    -   # Processing server (custom made)
        type: processing
        host: 127.0.0.1
        port: 7783
        pass: # A password here